### ISSUE TITLE
cbValue Not Defined

### ISSUE THREAD

**Issue by billy-odera** [jpmml/jpmml-catboost#2]
I get the below error when trying to execute the PMML file using a java method built 

```xml
<pmmlResponse>
  <statusCode>-1</statusCode>
  <statusDescription>org.jpmml.evaluator.MissingFieldException: Field "cbValue" is not defined
	at org.jpmml.evaluator.EvaluationContext.lookup(EvaluationContext.java:64)
  </statusDescription>
</pmmlResource>
```

**Comment by vruusmann** [comment]
High-level explanation - your input data record contains one or more missing values ("sparse input"), but the model expects all input fields to be present ("dense input").

Also, the exception message itself looks rather old. You're probably using some very outdated JPMML-Evaluator library version. Newer versions should provide more meaningful exception messages.

**Comment by billy-odera** [comment]
I have just compiled the JPMML-Catboost in a linux system and confirmed the data has no missing input

**Comment by vruusmann** [comment]
See the second part of my question - what is your JPMML-Evaluator library version?

**Comment by billy-odera** [comment]
1.4.3

**Comment by vruusmann** [comment]
> 1.4.3

Please upgrade.
